INSERT INTO time_of_prelection (id,start_of_prelection,end_of_prelection) VALUES (1,'10:00','11:45');
INSERT INTO time_of_prelection (id,start_of_prelection,end_of_prelection) VALUES (2,'12:00','13:45');
INSERT INTO time_of_prelection (id,start_of_prelection,end_of_prelection) VALUES (3,'14:00','15:45');
INSERT INTO prelection (id,amount_of_users,subject_of_prelection,time_of_prelection_id) VALUES (1,0, 'Java część 1',1);
INSERT INTO prelection (id,amount_of_users,subject_of_prelection,time_of_prelection_id) VALUES (2,0, 'Java część 2',2);
INSERT INTO prelection (id,amount_of_users,subject_of_prelection,time_of_prelection_id) VALUES (3,0, 'Java część 3',3);
INSERT INTO prelection (id,amount_of_users,subject_of_prelection,time_of_prelection_id) VALUES (4,0, '.Net część 1',1);
INSERT INTO prelection (id,amount_of_users,subject_of_prelection,time_of_prelection_id) VALUES (5,0, '.Net część 2',2);
INSERT INTO prelection (id,amount_of_users,subject_of_prelection,time_of_prelection_id) VALUES (6,0, '.Net część 3',3);
INSERT INTO prelection (id,amount_of_users,subject_of_prelection,time_of_prelection_id) VALUES (7,0, 'JavaScript część 1',1);
INSERT INTO prelection (id,amount_of_users,subject_of_prelection,time_of_prelection_id) VALUES (8,0, 'JavaScript część 2',2);
INSERT INTO prelection (id,amount_of_users,subject_of_prelection,time_of_prelection_id) VALUES (9,0, 'JavaScript część 3',3);
insert into user(id,email,login) values (1,'lala1@o2.pl','lala1');
insert into user(id,email,login) values (2,'lala2@o2.pl','lala2');
insert into user(id,email,login) values (3,'lala3@o2.pl','lala3');
